USE db;
CREATE TABLE USUARIOS (
  id_user BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(50) NOT NULL,
  nombre VARCHAR(255) NOT NULL
);

CREATE TABLE ADM (
  Id_adm BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTE (
  id_cl BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL,
  Dta_Nasc DATE NOT NULL,
  CPF VARCHAR(20) NOT NULL UNIQUE,
  RG VARCHAR(30) NOT NULL,
  CEL VARCHAR(20),
  DIRECCION VARCHAR(30),
  NUMCASA VARCHAR(20),
  SEXO VARCHAR(10),
  DTACADASTRO DATE,
  ESTADOCIVIL VARCHAR(20)
);

CREATE TABLE VENTAS (
  idVenta BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_cl BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (id_cl) REFERENCES CLIENTE (id_cl),
  id_user INT,
  FOREIGN KEY (id_user) REFERENCES USUARIOS (id_user) ON DELETE SET NULL,
  FechaVenta DATE NOT NULL,
  FechaVencimiento DATE,
  HoraVenta TIME,
  MontoVenta DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

