CREATE DATABASE db;
USE db;
CREATE TABLE USUARIOS (
  id_user BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(50) NOT NULL,
  nombre VARCHAR(255) NOT NULL
);

CREATE TABLE ADM (
  Id_adm BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  usuario VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTE (
  id_cl BIGINT UNSIGNED NOT NULL (0) AUTO_INCREMENT PRIMARY KEY,
  Nombre VARCHAR(50) NOT NULL (0),
  Dta_Nasc DATE NOT NULL,
  CPF VARCHAR(20) NOT NULL UNIQUE,
  SEXO VARCHAR(10) NOT NULL (0),
  CEL VARCHAR(20) NOT NULL,
  DIRECCION VARCHAR(30) NOT NULL,
  NUMCASA VARCHAR(20) NOT NULL,
  TIPO SANGUINEO VARCHAR (6) NOT NULL,
  NUM_CASA INT NOT NULL (0),
  COMPLEMENTO VARCHAR (30) NOT NULL,
  BARRIO VARCHAR (50) NOT NULL (0), 
  DTACADASTRO DATE NOT NULL ,
  ESTADOCIVIL VARCHAR(20) NOT NULL (0),
  DIA_NASCIMIENTO DATE NOT NULL,
  PAIS VARCHAR (60) NOT NULL
  

);

CREATE TABLE VENTAS (
  idVenta BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id_cl BIGINT UNSIGNED NOT NULL,
  FOREIGN KEY (id_cl) REFERENCES CLIENTE (id_cl),
  id_user INT,
  FOREIGN KEY (id_user) REFERENCES USUARIOS (id_user) ON DELETE SET NULL,
  FechaVenta DATE NOT NULL,
  FechaVencimiento DATE,
  HoraVenta TIME,
  MontoVenta DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

CREATE TABLE PRODUCTOS(

)
